---
title: "Материалы"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: united
---
## Многомерный статистический анализ в политологии
 
# Занятие 1
 
Тема: О чем курс и каковы правила игры? Введение в модели с фиксированными эффектами
  
<a href="MSA_intro.pdf" title=>Introduction</a> 
 
<a href="MSA_lecture1.pdf" title=>Lecture 1</a> 
 
<a href="MSA_seminar_1.pdf" title=>Seminar 1</a> 
 
Reading: 

<a href="Green et al., Dirty pool.pdf" title=>Dirty pool</a>  

<a href="https://yadi.sk/i/4YsEBveY1j4nUw" title=>Stock, Watson, Chapter 10</a>  

# Занятие 2
 
Тема: FE-models VS RE-models
 
<a href="MSA_lecture2.pdf" title=>Lecture 2</a>  
 
<a href="MSA_lab1.R" title=>Lab1</a>  

<a href="MSA_lab1.dta" title=>Data. Lab1</a>

# Занятие 3

Тема: FE-models (альтернативные спецификации, интерпретация, диагностики)

<a href="MSA_lecture3.pdf" title=>Lecture 3</a> 

<a href="MSA_lab2.R" title=>Lab2</a>

<a href="MSA_lab2.dta" title=>Data. Lab2</a>

Reading (optional):

<a href="Kropko, Kubinec, 2018.pdf" title=>Kropko, Kubinec, 2018</a>

<a href="Clark, Linzer, 2014.pdf" title=>Clark, Linzer, 2014</a>

# Занятие 4

Тема: FE-models + RE-models (практика)

<a href="MSA_lab3.R" title=>Lab3</a>

<a href="MSA_lab3.dta" title=>Data. Lab3</a>

# Занятие 5

Тема: проверочная работа по FE-, RE-models + первая лекция по mixed-effects models

<a href="MSA_test11.pdf" title=>Проверочная (1 вариант)</a>

<a href="MSA_test12.pdf" title=>Проверочная (2 вариант)</a>

# Занятие 6

Тема: спецификации моделей со смешанными эффектами (ME-models), интерпретация

<a href="MSA_lecture4.pdf" title=>Lecture 4</a>

<a href="MSA_seminar3.pdf" title=>Seminar 2</a>

<a href="MSA_hw.pdf" title=>Домашнее задание для тренировки</a>


# Занятие 7

Тема: ME-models: спецификация, оценивание и тестирование моделей

<a href="MSA_lecture5.pdf" title=>Lecture 5</a>

<a href="MSA_lab4(UPD).R" title=>Lab4(UPD)</a>

<a href="MSA_lab4.dta" title=>Data. Lab4</a>

Домашнее задание к 11 октября: 

1) прочитать стр. 218 -- 224 в этой <a href="Steenbergen,Jones, 2002.pdf" title=>статье</a> 

2) подумать то, насколько содержательно оправданны допущения моделей со смешанными эффектами 

3) критически осмыслить предложенное авторами обоснование для использования этого класса моделей 

# Занятие 8

Reading: 

<a href="https://yadi.sk/d/ci9V-ylSU4Kh3A" title=>Hox,читать только про спефикации моделей, глава 2</a>  

<a href="Bell et al., 2019.pdf" title=>Bell et al., 2019</a>  
Примечание: модели со смешанными эффектами обозначены в статье как within-between RE-model

<a href="BLUP.pdf" title=>BLUP, MLE & REML</a> 

Домашнее задание к 3 ноября. Написать reflection paper на одну из статей, приведенных ниже

<a href="Paper 1. Kaariainen, 2007.pdf" title=>Paper 1. Kaariainen, 2007</a>  

<a href="Paper 2. Ibsen et al., 2019.pdf" title=>Paper 2. Ibsen et al., 2019</a> 

# Занятие 9

Тема: ME-models: спецификация, оценивание и тестирование моделей применительно к панельным данным

<a href="MSA_lecture6.pdf" title=>Lecture 6</a>

<a href="MSA_lab5.R" title=>Lab5</a>

<a href="MSA_lab5.dta" title=>Data. Lab5</a>

# Занятие 10

Тема: проверочная работа по ME-моделям + дополнительно: визуализация ME-моделей

<a href="MSA_test2_1.pdf" title=>Проверочная 2 (1 вариант) </a> 
 
<a href="MSA_test2_2.pdf" title=>Проверочная 2 (2 вариант)</a> 
 
<a href="MSA_lab6.R" title=>Lab 6</a> 
 
<a href="MSA_lab6_1.dta" title=>MSA_lab6_1.dta</a> 

<a href="MSA_lab6_2.csv" title=>MSA_lab6_2.csv</a> 

# Занятие 11

Тема: Эндогенность. Введение

<a href="MSA_lecture7.pdf" title=>Lecture 7</a> 
 
<a href="MSA_seminar3.pdf" title=>Seminar 3</a> 

# Занятие 12

Тема: Эндогенность. Эксперименты. Оценивание treatment effect  

<a href="MSA_lecture8.pdf" title=>Lecture 8</a> 
 
<a href="MSA_seminar4.pdf" title=>Seminar 4</a> 

Тема: инструментальные переменные

Reading: 

<a href="https://yadi.sk/i/4YsEBveY1j4nUw" title=>Stock, Watson, Chapter 12</a>  


# Занятие 13 

Тема: инструментальные переменные

<a href="MSA_lab7.R" title=>Lab 7</a> 
 
<a href="MSA_lab7.Rda" title=>Lab 7. Data</a> 

## Анализ категориальных данных 

# CDA. Занятие 1

Тема: модели бинарного выбора

<a href="CDA_seminar1.pdf" title=>CDA. Seminar 1</a> 

Домашнее задание к 24 января: 

1) Reading: Стр. 34 - 52, 79 - 82 в <a href="Long.pdf" title=>Long. CDA</a> 

2) Дорешать задания 1, 2, 4 (пункты 4 и 5) из файла к семинару


